Let's start with "defer" statements. 
According to the Oxford dictionary, "defer" means "allowing someone else to decide or choose something, or with agreeing to follow someone elseâ€™s decision".

It's almost the same in the Go programming, A defer statement defers the execution of a function until the surrounding function returns. 

Let's get into some examples and understand what exactly the above statement means in terms of the Go language.

A simple code to print your full name in Go is 


```
package main

import "fmt"

func main() {
	fmt.Println("Replace this with your full name")
}
```

Now, let's use defer statement and print your first, middle names and then last name.

```
package main

import "fmt"

func main() {
	defer fmt.Println("Replace this with your last name")

	fmt.Println("Replace this with your first and middle name")
}

```

By having a glance at the above code, you should have understood that the above function first prints your first, middle name and then your last name.
That's what a defer statement does.

To make it a little bit more complex, try to guess what happens when there are multiple defer statements before reading further.

Most probably, based on my assumption, you would have already heard about Stack data structure. The stack follows the LIFO approach i.e., Last In First Out.
When there are multiple defer calls in a function, those deferred calls will get pushed onto a stack and when a function's execution is done, all those calls are 
executed from the stack(last in first out approach).

I will utilize the same example from Go Playground because numbers make it easy to understand. The for loop below prints the numbers from 1 to 10 in reverse
order despite the for loop executing from 1 to 10. Let's see how defer statement helps in achieving this.

```
package main
import "fmt"

func main() {
	for i := 0; i < 10; i++ {
		defer fmt.Println(i)
	}
}
```

This is going to print 9 8 7 ... 0 because of the stacking technique utilized by defer statement.

**Now, after all these examples, you might think what exactly is the need for "defer" statements in real-life and can't we live without them?**

Generally, there are many use cases in the Software world, where you need to read from a file and then need to write to a file. So, let's say you opened
a file(through Go lang) and read some data then unfortunately you got an error. In this case, you need to somehow close the file you opened or else it might
get corrupted or memory leakage can happen.

In this scenario, if we had a defer statement that has a command to close the file before opening it, then we do need to worry if an error occurs in the function call.

In terms of Go code:

```
source = os.Open("source file name") //opens the sourcefile given

//perform some actions on the file
// Even if some error pops up, the below defer statement gets executed and closes the file

defer source.Close()
```

I understand that it's so much for a just single "defer" statement, but it took so long to grasp and make it understandable to you in simple terms.

Along with defer, there are two more statements named **Panic** and **Recover** which are regularly used.

Understanding all these three statements and how and when developers use these words and when can we use them as a combination was a little challenging and took more time than I expected.


Coming to **Panic**: It is a built-in function that stops the ordinary flow of control and begins panicking. 

Let's say there is a function named random_function and has some panic function or statement in it.
When the random_function calls panic, the execution of random_function is terminated, all defer functions in random_function are run normally,
and random_function is returned to its caller. random_function then acts like a panic call to the caller. The procedure is repeated until all functions in the current goroutine return, at which time the program fails.

The **recover** statement is used in conjunction with the panic statement to handle and recover from runtime errors that would otherwise crash the program.

When the Go runtime encounters a panic statement, it will unwind the stack, performing deferred functions and handing control to the earliest recover statement. The recover method then halts the stack unwinding and returns the value given to the panic statement.


For example, in terms of code:

```
package main
import "fmt"

func main() {
	defer func() {
		if r := recover(); r != nil {
			fmt.Println("I called Recover")
		}
	}()
	
	panic("I started to panic!")
	
	// This line will not be executed because of the above panic statement and then the recover function in defer statement gets called and prints "I called Recover"
	fmt.Println("This line will not be printed")
}

```

It's important to note that the recover function can only be called inside a deferred function. If it's called outside of a deferred function, it will simply return nil.







